Config = {
    color = {
        "White",
        "Red",
        "Green",
        "Blue",
        "White",
        "Yellow",
        "Light Red",
        "Violet",
        "Pink",
        "Light Orange",
        "Light Brown",
        "Light Green",
        "Light Blue",
        "Light Purple",
        "Dark Purple",
        "Cyan",
        "Light Yellow",
        "Orange",
        "Light Blue",
        "Dark Pink",
        "Dark Yellow",
        "Dark Orange",
        "Light Gray",
        "Light Pink",
        "Lemon Green",
        "Forest Green",
        "Electric Blue",
        "Bright Purple",
        "Dark Yellow",
        "Dark Blue",
        "Dark Cyan",
        "Light Brown",
        "Light Blue",
        "Light Yellow",
        "Light Pink",
        "Light Red",
        "Beige",
        "White",
        "Blue",
        "Light Gray",
        "Dark Gray",
        "Pink Red",
        "Blue",
        "Light Green",
        "Light Orange",
        "White",
        "Gold",
        "Orange",
        "Brilliant Rose",
        "Blue",
        "Medium Purple",
        "Salmon",
        "Dark Green",
        "Blizzard Blue",
        "Oracle Blue",
        "Silver",
        "Brown",
        "Blue",
        "East Bay",
        "Red",
        "Yellow Orange",
        "Mulberry Pink",
        "Alto Gray",
        "Jelly Bean Blue",
        "Dark Orange",
        "Mamba",
        "Yellow Orange",
        "Blue",
        "Blue",
        "Green",
        "Yellow Orange",
        "Yellow Orange",
        "Transparent Black",
        "Yellow Orange",
        "Blue",
        "Red",
        "Deep red",
        "Blue",
        "Oracle Blue",
        "Transparent Red",
        "Transparent Blue",
        "Orange",
        "Light Green",
        "Purple",
        "Blue",
        "Transparent Black"
    }
}